#include "AboutPage.h"
#include "ui_AboutPage.h" // IMPORTANT: This file is auto-generated by Qt

AboutPage::AboutPage(QWidget *parent) :
    QDialog(parent),
    ui(new Ui::AboutPage)
{
    ui->setupUi(this);

    // Optional: Removes the "?" context help button from the title bar
    // for a cleaner, more modern look.
    setWindowFlags(windowFlags() & ~Qt::WindowContextHelpButtonHint);
}

AboutPage::~AboutPage()
{
    delete ui;
}